Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.56.20"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end
  
  config.vm.provision "ansible_local" do |ansible|
   ansible.playbook ="provisioning/playbook.yml"
   #ansible.inventory_path = "inventory"
  end
end
