Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "private_network", ip: "192.168.56.20"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
    end
  
  config.vm.provision "shell", inline: <<-SHELL
      sudo apt update
  SHELL

  config.vm.provision "ansible_local" do |ansible|
   ansible.playbook ="provisioning/playbook.yml"
  end
end
