version: '3.8'
services:
  web:
    build: ./frontend/
    container_name: unir_act2_web
    ports:
      - "8080:80"
    networks:
      - unir-app-network
    depends_on:
      - api
    restart: unless-stopped
  api:
    build: ./backend/
    container_name: unir_act2_api
    ports:
      - "8000:80"
    networks:
      # ------ ¡CAMBIO IMPORTANTE AQUÍ! ------
      # Asignamos una IP estática dentro de la red app-network
      unir-app-network:
        ipv4_address: 172.20.0.11
    depends_on:
      - db
    environment:
      - DB_HOST=172.20.0.10
      - DB_PORT=5432
      - DB_NAME=unir
      - DB_USER=unir
      - DB_PASSWORD=unirAdmin
    restart: unless-stopped
  db:
    build: ./persistencia/
    container_name: unir_act2_db
    environment:
      - POSTGRES_PASSWORD=unirAdmin
      - POSTGRES_DB=unir
      - POSTGRES_USER=unir
    volumes:
      - db-pg-data:/var/lib/postgresql
    networks:
      # ------ ¡CAMBIO IMPORTANTE AQUÍ! ------
      # Asignamos una IP estática dentro de la red app-network
      unir-app-network:
        ipv4_address: 172.20.0.10
    ports:
      - "5232:5432"
    restart: unless-stopped
# Red para la comunicación entre contenedores
networks:
  unir-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
# Volumen para persistir los datos de la base de datos
volumes:
  db-pg-data:
    driver: local
