# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "puppetwordpress" do |puppetwordpress|
    puppetwordpress.vm.network "forwarded_port", guest: 80, host: 8080
    puppetwordpress.vm.network "private_network", ip: "192.168.10.106"
    puppetwordpress.vm.hostname = "puppetwordpress"
    puppetwordpress.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "puppetwordpress"
    end
    puppetwordpress.vm.provision "shell", inline: <<-SHELL
      sudo wget https://apt.puppetlabs.com/puppet6-release-bionic.deb
      sudo dpkg -i puppet6-release-bionic.deb
      sudo curl https://apt.puppet.com/DEB-GPG-KEY-future | sudo gpg -o /etc/apt/trusted.gpg.d/puppet.gpg --dearmor
      sudo apt-get update
      sudo apt-get install -y puppet-agent
    SHELL
    puppetwordpress.vm.provision "puppet" do |puppet|
      puppet.module_path = "modules"        
      puppet.manifests_path = "manifests"   # Default
      puppet.manifest_file = "actividad1.pp"   # Default
    end
  end  
end